# Generated by Django 5.2.11 on 2026-05-12 16:42

import django_pgai.db.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('overview', django_pgai.db.field.VectorizedTextField(vectorizer_name='movie_overview_qwen3')),
                ('overview_mxbai', django_pgai.db.field.VectorizedTextField(source_field='overview', vectorizer_name='movie_overview_mxbai')),
                ('overview_minilm', django_pgai.db.field.VectorizedTextField(source_field='overview', vectorizer_name='movie_overview_minilm')),
                ('overview_snowflake', django_pgai.db.field.VectorizedTextField(source_field='overview', vectorizer_name='movie_overview_snowflake')),
                ('genres', models.TextField(blank=True, default='')),
                ('producer', models.TextField(blank=True, default='')),
                ('cast', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
