# Generated by Django 6.0.2 on 2025-10-04 10:34

import django_pgai.db.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMxbai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('overview', django_pgai.db.field.VectorizedTextField(chunking_method='recursive', chunking_overlap=30, chunking_size=300, embedding_dimensions=1024, embedding_model='mxbai-embed-large:latest')),
                ('genres', models.TextField(blank=True, default='')),
                ('producer', models.TextField(blank=True, default='')),
                ('cast', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Movie (Mxbai)',
                'verbose_name_plural': 'Movies (Mxbai)',
            },
        ),
        migrations.CreateModel(
            name='MovieQwen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('overview', django_pgai.db.field.VectorizedTextField(chunking_method='recursive', chunking_overlap=30, chunking_size=300, embedding_dimensions=1024, embedding_model='qwen3-embedding')),
                ('genres', models.TextField(blank=True, default='')),
                ('producer', models.TextField(blank=True, default='')),
                ('cast', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Movie (Qwen)',
                'verbose_name_plural': 'Movies (Qwen)',
            },
        ),
        migrations.CreateModel(
            name='WikiArticleMiniLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('title', models.TextField()),
                ('text', django_pgai.db.field.VectorizedTextField(chunking_method='recursive', chunking_overlap=30, chunking_size=300, embedding_dimensions=384, embedding_model='all-minilm')),
            ],
            options={
                'verbose_name': 'Wiki Article (MiniLM)',
                'verbose_name_plural': 'Wiki Articles (MiniLM)',
            },
        ),
        migrations.CreateModel(
            name='WikiArticleSnowflake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('title', models.TextField()),
                ('text', django_pgai.db.field.VectorizedTextField(chunking_method='recursive', chunking_overlap=50, chunking_size=350, embedding_dimensions=1024, embedding_model='snowflake-arctic-embed')),
            ],
            options={
                'verbose_name': 'Wiki Article (Snowflake)',
                'verbose_name_plural': 'Wiki Articles (Snowflake)',
            },
        ),
    ]
