FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libatomic1 \
    && rm -rf /var/lib/apt/lists/*

ENV UV_PYTHON_DOWNLOADS=0
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /src/app
RUN uv venv --system-site-packages && \
    uv pip install ipython dotenv

ENV PATH="/src/app/.venv/bin:$PATH"

CMD ["/bin/bash"]
